const ts = s => {
  const [minsec, ms = "0"] = s.split(".");
  const [m, sec] = minsec.split(":").map(Number);
  return m * 60 + sec + Number("0." + ms);
};

export const sessions = [
  {
    participantId: "rN2Kw9mLqTbXcVpAz7YeH4sJ1fD8",
    recordingId: "1744214383241",
    videoFile: "1744214383241-study-recording.mp4",
    navOffset: 0,
    events: [
      { t: ts("0:00"),   screenId: "tab.learn" },
      { t: ts("01:53"),  screenId: "tab.profile" },
      { t: ts("02:40"),  screenId: "tab.learn" },
      { t: ts("02:46.75"),  screenId: "module.bar_charts.welcome" },
      { t: ts("03:03.8"),  screenId: "tab.learn" },
      { t: ts("03:11.25"),  screenId: "module.bar_charts.welcome" },
      { t: ts("03:36.09"),  screenId: "module.bar_charts.q1" },
      { t: ts("05:17.14"),  screenId: "module.bar_charts.q2" },
      { t: ts("05:50.14"),  screenId: "module.bar_charts.q3" },
      { t: ts("06:06.02"),  screenId: "module.bar_charts.q4" },
      { t: ts("07:52.26"),  screenId: "module.bar_charts.q5" },
      { t: ts("08:22.59"),  screenId: "module.bar_charts.completion" },
      { t: ts("08:50.40"),  screenId: "module.bar_charts.review.q4" },
      { t: ts("08:57.38"),  screenId: "module.bar_charts.completion" },
      { t: ts("08:59.425"),  screenId: "module.bar_charts.review.q2" },
      { t: ts("09:02.21"),  screenId: "module.bar_charts.completion" },
      { t: ts("09:06.41"),  screenId: "tab.learn" },
      { t: ts("09:16.15"),  screenId: "tab.profile" },
      { t: ts("09:27.031"),  screenId: "tab.learn" },
    ],
    answers: [
      {
        id: "randomid1",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 0,
        selectedAnswerIndex: 1,
        correctAnswerIndex: 1,
        secondAttempt: false,
        timestamp: "2026-04-09T14:22:18.000Z",
        navigationDocId: "nav_bar_charts_q1",
        navEnter: ts("03:36.09"),
        navExit:  ts("05:17.13"),
      },
      {
        id: "randomid2",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 1,
        selectedAnswerIndex: 1,
        correctAnswerIndex: 1,
        secondAttempt: false,
        timestamp: "2026-04-09T14:23:05.000Z",
        navigationDocId: "nav_bar_charts_q2",
        navEnter: ts("05:17.14"),
        navExit:  ts("05:50.13"),
      },
      {
        id: "randomid3",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 2,
        selectedAnswerIndex: 0,
        correctAnswerIndex: 0,
        secondAttempt: false,
        timestamp: "2026-04-09T14:24:41.000Z",
        navigationDocId: "nav_bar_charts_q3",
        navEnter: ts("05:50.14"),
        navExit:  ts("06:06.01"),
      },
      {
        id: "randomid4",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 3,
        selectedAnswerIndex: 2,
        correctAnswerIndex: 1,
        secondAttempt: false,
        timestamp: "2026-04-09T14:24:41.000Z",
        navigationDocId: "nav_bar_charts_q4",
        navEnter: ts("06:06.02"),
        navExit:  ts("07:52.25"),
      },
      {
        id: "randomid5",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 4,
        selectedAnswerIndex: 1,
        correctAnswerIndex: 1,
        secondAttempt: false,
        timestamp: "2026-04-09T14:24:41.000Z",
        navigationDocId: "nav_bar_charts_q4",
        navEnter: ts("07:52.26"),
        navExit:  ts("08:22.55"),
      },
    ],
  },
  {
    participantId: "hW5Tz3nCkFdRmUqBv6XsL8jY2eA0",
    recordingId: "1744819204831",
    videoFile: "1744819204831-study-recording.mp4",
    navOffset: 0,
    events: [
      { t: 0.0,   screenId: "tab.learn" },
      { t: 2.3,   screenId: "module.bar_charts.intro" },
      { t: 7.8,   screenId: "module.bar_charts.question_1" },
      { t: 18.5,  screenId: "module.bar_charts.question_2" },
      { t: 30.1,  screenId: "module.bar_charts.completion" },
      { t: 33.6,  screenId: "tab.learn" },
      { t: 35.9,  screenId: "module.pie_charts.intro" },
      { t: 41.4,  screenId: "module.pie_charts.question_1" },
      { t: 55.7,  screenId: "module.pie_charts.question_2" },
      { t: 72.2,  screenId: "module.pie_charts.completion" },
      { t: 75.0,  screenId: "tab.profile" },
    ],
    answers: [
      {
        id: "iJ9rKdX3nMwBt7Lp",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 0,
        selectedAnswerIndex: 3,
        correctAnswerIndex: 3,
        secondAttempt: false,
        timestamp: "2026-04-16T10:08:55.000Z",
        navigationDocId: "nav_bar_charts_q0",
        navEnter: 7.8,
        navExit:  18.0,
      },
      {
        id: "kL2sOeY7fNvCu4Qa",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 1,
        selectedAnswerIndex: 1,
        correctAnswerIndex: 1,
        secondAttempt: false,
        timestamp: "2026-04-16T10:09:44.000Z",
        navigationDocId: "nav_bar_charts_q1",
        navEnter: 18.5,
        navExit:  29.8,
      },
      {
        id: "mN4uPfZ8hOwDv6Rb",
        unitName: "Categorical Charts",
        moduleName: "Pie Charts",
        moduleRoute: "unit1/pie_charts",
        questionIndex: 0,
        selectedAnswerIndex: 0,
        correctAnswerIndex: 2,
        secondAttempt: false,
        timestamp: "2026-04-16T10:11:22.000Z",
        navigationDocId: "nav_pie_charts_q0",
        navEnter: 41.4,
        navExit:  55.2,
      },
      {
        id: "oP6wQgA1jRxEy3Sc",
        unitName: "Categorical Charts",
        moduleName: "Pie Charts",
        moduleRoute: "unit1/pie_charts",
        questionIndex: 1,
        selectedAnswerIndex: 3,
        correctAnswerIndex: 3,
        secondAttempt: false,
        timestamp: "2026-04-16T10:12:58.000Z",
        navigationDocId: "nav_pie_charts_q1",
        navEnter: 55.7,
        navExit:  71.8,
      },
    ],
  },
];