const ts = s => {
  const [minsec, ms = "0"] = s.split(".");
  const [m, sec] = minsec.split(":").map(Number);
  return m * 60 + sec + Number("0." + ms);
};

export const sessions = [
  {
    participantId: "rN2Kw9mLqTbXcVpAz7YeH4sJ1fD8",
    recordingId: "1744214383241",
    videoFile: "1744214383241-study-recording.mp4",
    navOffset: 0,
    events: [
      { t: ts("0:00"),   screenId: "tab.learn" },
      { t: ts("01:53"),  screenId: "tab.profile" },
      { t: ts("02:40"),  screenId: "tab.learn" },
      { t: ts("02:46.75"),  screenId: "module.bar_charts.welcome" },
      { t: ts("03:03.8"),  screenId: "tab.learn" },
      { t: ts("03:11.25"),  screenId: "module.bar_charts.welcome" },
      { t: ts("03:36.09"),  screenId: "module.bar_charts.q1" },
      { t: ts("05:17.14"),  screenId: "module.bar_charts.q2" },
      { t: ts("05:50.14"),  screenId: "module.bar_charts.q3" },
      { t: ts("06:06.02"),  screenId: "module.bar_charts.q4" },
      { t: ts("07:52.26"),  screenId: "module.bar_charts.q5" },
      { t: ts("08:22.59"),  screenId: "module.bar_charts.completion" },
      { t: ts("08:50.40"),  screenId: "module.bar_charts.review.q4" },
      { t: ts("08:57.38"),  screenId: "module.bar_charts.completion" },
      { t: ts("08:59.425"),  screenId: "module.bar_charts.review.q2" },
      { t: ts("09:02.21"),  screenId: "module.bar_charts.completion" },
      { t: ts("09:06.41"),  screenId: "tab.learn" },
      { t: ts("09:16.15"),  screenId: "tab.profile" },
      { t: ts("09:27.031"),  screenId: "tab.learn" },
    ],
    answers: [
      {
        id: "randomid1",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 0,
        selectedAnswerIndex: 1,
        correctAnswerIndex: 1,
        secondAttempt: false,
        timestamp: "2026-04-09T14:22:18.000Z",
        navigationDocId: "nav_bar_charts_q1",
        navEnter: ts("03:36.09"),
        navExit:  ts("05:17.13"),
      },
      {
        id: "randomid2",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 1,
        selectedAnswerIndex: 1,
        correctAnswerIndex: 1,
        secondAttempt: false,
        timestamp: "2026-04-09T14:23:05.000Z",
        navigationDocId: "nav_bar_charts_q2",
        navEnter: ts("05:17.14"),
        navExit:  ts("05:50.13"),
      },
      {
        id: "randomid3",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 2,
        selectedAnswerIndex: 0,
        correctAnswerIndex: 0,
        secondAttempt: false,
        timestamp: "2026-04-09T14:24:41.000Z",
        navigationDocId: "nav_bar_charts_q3",
        navEnter: ts("05:50.14"),
        navExit:  ts("06:06.01"),
      },
      {
        id: "randomid4",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 3,
        selectedAnswerIndex: 2,
        correctAnswerIndex: 1,
        secondAttempt: false,
        timestamp: "2026-04-09T14:24:41.000Z",
        navigationDocId: "nav_bar_charts_q4",
        navEnter: ts("06:06.02"),
        navExit:  ts("07:52.25"),
      },
      {
        id: "randomid5",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 4,
        selectedAnswerIndex: 1,
        correctAnswerIndex: 1,
        secondAttempt: false,
        timestamp: "2026-04-09T14:24:41.000Z",
        navigationDocId: "nav_bar_charts_q4",
        navEnter: ts("07:52.26"),
        navExit:  ts("08:22.55"),
      },
    ],
  }
];