export const sessions = [
  {
    participantId: "6eEP7j4VAeXkmBrAzk38sD5G0oE3",
    recordingId: "1775762473577",
    videoFile: "1775762473577-study-recording.mp4",
    navOffset: 0,
    events: [
      { t: 0.0,   screenId: "tab.learn" },
      { t: 2.925, screenId: "module.pie_charts.completion" },
      { t: 4.97,  screenId: "tab.learn" },
      { t: 6.0,   screenId: "tab.profile" },
    ],
    answers: [
      {
        id: "3as0Mzw0ChtoXxkjaFe0",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 0,
        selectedAnswerIndex: 1,
        correctAnswerIndex: 1,
        secondAttempt: false,
        timestamp: "2026-03-23T20:50:10.000Z",
        navigationDocId: "nav_bar_charts_q0",
        navEnter: 0.8,
        navExit:  2.9,
      },
      {
        id: "Ka0queAou32bHIxzwNU9",
        unitName: "Categorical Charts",
        moduleName: "Bar Charts",
        moduleRoute: "unit1/bar_charts",
        questionIndex: 1,
        selectedAnswerIndex: 0,
        correctAnswerIndex: 2,
        secondAttempt: false,
        timestamp: "2026-03-23T20:51:05.000Z",
        navigationDocId: "nav_bar_charts_q1",
        navEnter: 3.5,
        navExit:  4.8,
      },
      {
        id: "Y9QYb8dH0fK5nugnNzgMn",
        unitName: "Categorical Charts",
        moduleName: "Pie Charts",
        moduleRoute: "unit1/pie_charts",
        questionIndex: 0,
        selectedAnswerIndex: 2,
        correctAnswerIndex: 2,
        secondAttempt: false,
        timestamp: "2026-03-23T20:52:30.000Z",
        navigationDocId: "nav_pie_charts_q0",
        navEnter: 5.0,
        navExit:  6.5,
      }
    ],
  },
];